### PR TITLE
various small fixes and enhancements

### PR DESCRIPTION
**Pull request by drzraf**
cf: list of commits below

### CODE REVIEW

**Comment by drzraf** [comment]
any plan to push it?
Should be straightforward and using HTTPS when possible + fixing the local-CIDR detection are nice.

**Comment by trick77** [comment]
Absolutely, thanks!

**Comment by gagomap** [comment]
I have updated this script. But when i run update-blacklist.sh, it show:

```bash
Can't load configuration file

```

Because you forget to add ipset-blacklist.conf location path

I have fixed it. But i change something then i can't make a pull request.
Please check !

```bash
IP_BLACKLIST_CONF="/etc/ipset-blacklist/ipset-blacklist.conf"

if [[ -z "$IP_BLACKLIST_CONF" ]] || ! source "$IP_BLACKLIST_CONF"; then
    echo "Can't load configuration file $IP_BLACKLIST_CONF"
    exit 1
fi
```

**Comment by gagomap** [comment]
This is my install file for ipset and your script:

```bash
#!/bin/sh

#Install prereqs
for command in ipset iptables egrep grep curl sort uniq wc
do
if ! which $command > /dev/null; then
echo "Installing $command"
apt-get install -y $command
fi
done

#Make folder
mkdir -p /etc/ipset-blacklist

#Put update script in cron daily to keep it up to date

\curl -sSL https://raw.githubusercontent.com/trick77/ipset-blacklist/master/ipset-blacklist.conf > /etc/ipset-blacklist/ipset-blacklist.conf

\curl -sSL https://raw.githubusercontent.com/trick77/ipset-blacklist/master/update-blacklist.sh > /etc/cron.daily/update-blacklist.sh
chmod +x /etc/cron.daily/update-blacklist.sh

#Create blacklist 
#ipset create blacklist hash:net family inet hashsize 131072 maxelem 262144

#Fill up the blacklist set
/etc/cron.daily/update-blacklist.sh
```

**Comment by mgaulton** [comment]
Can we go back to variables for hashsize? I use 1048575 :)

**Comment by gagomap** [comment]
@mgaulton : open update-blacklist.sh and edit these lines:

```bash
# create the ipset if needed (or abort if does not exists and FORCE=no)
if ! ipset list -n|command grep -q "$IPSET_BLACKLIST_NAME"; then
    if [[ ${FORCE:-no} != yes ]]; then
	echo >&2 "Error: ipset does not exist yet, add it using:"
	echo >&2 "# ipset create $IPSET_BLACKLIST_NAME -exist hash:net family inet hashsize ${HASHSIZE:-65536}"
	exit 1
    fi
    if ! ipset create "$IPSET_BLACKLIST_NAME" -exist hash:net family inet hashsize "${HASHSIZE:-65536}"; then
	echo >&2 "Error: while creating the initial ipset"
	exit 1
    fi
fi
```
```bash
# family = inet for IPv4 only
cat >| "$IP_BLACKLIST_RESTORE" <<EOF
create $IPSET_TMP_BLACKLIST_NAME -exist hash:net family inet hashsize ${HASHSIZE:-65536} maxelem ${MAXELEM:-65536}
create $IPSET_BLACKLIST_NAME -exist hash:net family inet hashsize ${HASHSIZE:-65536} maxelem ${MAXELEM:-65536}
EOF
```

**Comment by drzraf** [comment]
@mgaulton before PR #25 it use to have a predefined value of 65536 in the first lines of the file.
Now, the predefined value is not set there anymore **but** it's still a variable, thus nothing stops you from
using one of the following :
* ``$ HASHSIZE=foo update-blacklist.sh``
* ``$ export HASHSIZE=foo; update-blacklist.sh``
* ``$ echo HASHSIZE=foo >>  ipset-blacklist.conf; update-blacklist.sh``

Lastly, inside the crontab file:
```
HASHSIZE=foo
0 0 * * sun update-blacklist.sh
```

**Comment by mgaulton** [comment]
@drzraf ahhh i missed that. i was expecting to find it in the conf already like it used to be. Thanks.

**Comment by mgaulton** [comment]
@gagomap yes, that's what I ended up doing, it just felt messy.

**Pull request merged**
